name = "api"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
  { binding = "BUCKET", id = "", preview_id = "06c7a7f729584e2ab861c767072ab15b" }
]